language: python
sudo: false
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
install:
  - python bootstrap.py
  - ./bin/buildout
script:
  - bin/coverage run bin/test
after_success:
  - pip install coveralls
  - coveralls
notifications:
    email: false
